services:
  web:
    env_file:
      - ./.env.local
    build:
      context: ./web/nextjs
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment: 
      - NODE_ENV=production
      - PORT=3001
      - SERVER_HOST=http://server:4003
    networks:
      - shared

  # The server is the backend of the application
  # It is not exposed to the public internet and has no auth
  server:
    env_file:
      - ./.env.local
    build:
      context: ./server/nodejs
      dockerfile: Dockerfile
    environment: 
      - NODE_ENV=production
      - PORT=4003
    networks:
      - shared

networks:
  shared:
